FIELD_MAP = {
    "1  Name Last": "last_name",
    "1  Name First": "first_name",
    "1  Name MI": "middle_initial",
    "2  Social Security Number": "ssn",
    "Month": "dob_month",
    "Day": "dob_day",
    "Year": "dob_year",
    "6  Address Street Apt  PO Box": "address",
    "City": "city",
    "Combo Box2": "state",
    "Zip": "zip",
    "Ph Area 1": "phone_area",
    "Ph Exchange 1": "phone_prefix",
    "Ph Number 1": "phone_line",
    "Cancer Diagnosis": "cancer_checkbox",
    "Cancer Specific Diagnosis 1": "diagnosis",
    "Montha": "diag_month",
    "Daya": "diag_day",
    "Yeara": "diag_year",
    "Date": "today_date",
}
